version: 0.1

phases:
  install:
    commands:
      - pacman -S nodejs npm
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
